blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # path('about/', views.about, name='blog-about'),
    path('gallery/', views.gallery, name='blog-gallery'),
]

core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# from .views import (
#     PostListView,
#     PostDetailView,
#     PostCreateView,
#     PostUpdateView,
#     PostDeleteView,
#     UserPostListView
# )
from . import views

urlpatterns = [
    # path('', PostListView.as_view(), name='blog-home'),
    # path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    # path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    # path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # path('about/', views.about, name='blog-about'),

    path('', views.home, name='core-home'),
    # path('', views.Home.as_view(), name='core-home'),
# Online Library
    path('class/subjects/', views.subject_list, name='subject_list'),
    path('subjects/<int:pk>/', views.delete_subject, name='delete_subject'),
    path('class/subjects/edit/<int:id>', views.edit_subject, name='edit_subject'),
    path('class/subjects/update/<int:id>', views.update_subject, name='update_subject'),
# Online Library view
    path('class/subjects/list', views.SubjectListView.as_view(), name='class_subject_list'),
    path('class/subjects/upload/', views.UploadSubjectView.as_view(), name='class_upload_subject'),
    # path('class/subjects/upload/', views.upload_book, name='class_upload_subject'),
# Online Lookup view
    path('api/lookup/', views.LookupAPIView.as_view()),
    path('error403/', views.error403, name='core-403'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miika/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from miika.views import home
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', home, name='miika-home'),
    path('about/', views.about, name='miika-about'),
    path('contact/', views.contact, name='miika-contact'),
    # path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('core/', include('core.urls')),
    # path('chat/', include('chat.urls')),
    # path('fileupload/', include('fileupload.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

from django.conf import settings
from datetime import datetime
from django.utils import timezone

from django.contrib.auth.models import User


YES_NO = (
        ('Yes', 'Yes'),
        ('No','No'),
    )


class LookupType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    active = models.CharField(max_length=10, choices = YES_NO)

    def __str__(self):
        return self.name


    class Meta:
        db_table = "lookuptype"
        verbose_name = 'Lookup Type'
        verbose_name_plural = 'Lookup Types'


class Lookup(models.Model):
    id = models.AutoField(primary_key=True)
    lookup_type = models.ForeignKey(LookupType, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    value = models.CharField(max_length=500)
    sequence = models.IntegerField(null=True, blank=True)
    active = models.CharField(max_length=10, choices = YES_NO)

    def __str__(self):
        return self.value

    class Meta:
        db_table = "lookup"

def fileLocation(instance, filename):
        return 'uploads/{0}/{1}/{2}/{3}/{4}'.format(instance.year_level, instance.subject_code, instance.subject_type, instance.lesson_number, filename)

# def fileLocationCover(instance, filename):
#     return 'uploads/{0}/{1}/{2}/'.format(instance.year_level, instance.subject_code, instance.lesson_number)

class Subject(models.Model):
    # year_level = models.CharField(max_length=100)
    year_level = models.CharField(max_length=100, null=True, blank=True)
    subject_code = models.CharField(max_length=100)
    subject_description = models.CharField(max_length=500)
    lesson_number = models.IntegerField(null=True, blank=True)
    lesson_name = models.CharField(max_length=100)
    subject_type = models.CharField(max_length=100, null=True, blank=True)
    # title = models.CharField(max_length=100)
    # author = models.CharField(max_length=100)
    # pdf = models.FileField(upload_to='subjects/pdfs/')
    # cover = models.ImageField(upload_to='subjects/covers/', null=True, blank=True)
    cover = models.ImageField(upload_to='uploads/covers/', null=True, blank=True)
    file = models.FileField(upload_to=fileLocation, null=True, blank=True)

    # todo: must come from create/update mixin. Resolve circular reference.
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='create')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='update')

    def __str__(self):
        # return self.title
        return self.subject_code

    def delete(self, *args, **kwargs):
        # self.pdf.delete()
        # self.cover.delete()
        self.file.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)

core/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from rest_framework import generics
from .serializers import LookupSerializers
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)


from .forms import SubjectForm
from .models import Subject, LookupType, Lookup

from django.conf import settings
# from .models import *

# def home(request):
#     return render(request, 'core/home.html', {'title': 'About'})

def check_group(user):
    # First check if the user belongs to the group
    if user.groups.filter(name='miika_admin').exists():
        return True
# @login_required
# @user_passes_test(check_group, login_url='/post/error403/')

class check_group_mixin(UserPassesTestMixin):
    def test_func(self):
        if self.request.user.groups.filter(name='miika_admin').exists():
            return True


@login_required
def home(request):
    context = {'subjects': Subject.objects.all()}
    return render(request, 'core/home.html', context)

    # if not request.user.is_authenticated:
    #     print("not valid")
    #     # return render(request, 'users/login.html')
    #     return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    # else:
    #     # context = {'subjects': Subject.objects.all()}
    #     return render(request, 'core/home.html', context)



# def about(request):
#     return render(request, 'core/about.html', {'title': 'About'})

def subject_list(request):
    subjects = Subject.objects.all()
    return render(request, 'core/class_subject_list.html', {
        'subjects': subjects
    })



@user_passes_test(check_group, login_url='/core/error403/')

def delete_subject(request, pk):
    if request.method == 'POST':
        subject = Subject.objects.get(pk=pk)
        subject.delete()
    return redirect('subject_list')

def edit_subject(request, id):
    subject = Subject.objects.get(id=id)
    form = SubjectForm(instance=subject)
    context = {
        'subject': subject,
        'form': form,
    }
    return render(request, 'core/edit_subject.html', context=context)

# def update_subject(request, id):
#     subject = Subject.objects.get(id=id)
#     # form = TestForm(instance=deliveryreceipt)
#     form = SubjectForm(request.POST, instance = subject)
#     if form.is_valid():
#         form.save()
#         # rmc 11/08/2021 - Start
#         created_updated(Subject, request)
#         # rmc 11/08/2021 - End
#         return redirect("/core")
#     else:
#         messages.error(request, "Error")
#         print(messages.error(request, "Error"))
#         return render(request, 'core/pagedisplayerror.html', {'form': form})
#     return render(request, 'core/edit_subject.html', {'subject': subject})

def update_subject(request, id):
    subject = Subject.objects.get(id=id)
    if request.method=='POST':
        form = SubjectForm(request.POST, request.FILES, instance = subject)
        if form.is_valid():
            form.save()
             # rmc 11/08/2021 - Start
            created_updated(Subject, request)
            # rmc 11/08/2021 - End
            return redirect("/core")
        else:
            messages.error(request, "Error")
            print(messages.error(request, "Error"))
            return render(request, 'core/pagedisplayerror.html', {'form': form})
    else:
         form = SubjectForm(instance=subject)
    return render(request, 'core/edit_subject.html', {'subject': subject})

def created_updated(model, request):
    obj = model.objects.latest('pk')
    print(obj.created_by)
    if obj.created_by is None:
        obj.created_by = request.user
        # obj.dispatcher = request.user
    obj.updated_by = request.user
    obj.save()

def error403(request):
    return render(request, "core/error403.html", {'title':'error403'})

class SubjectListView(ListView):
    model = Subject
    template_name = 'core/class_subject_list.html'
    context_object_name = 'subjects'


# @login_required
# @method_decorator(login_required, name='dispatch')
# @user_passes_test(check_group, login_url='/core/error403/')

# def upload_book(request):
#     if request.method == 'POST':
#         form = SubjectForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('class_subject_list')
#     else:
#         form = SubjectForm()
#     return render(request, 'core/upload_subject.html', {
#         'form': form
#     })


# class UploadSubjectView(LoginRequiredMixin,CreateView):
@method_decorator(login_required, name='dispatch')
class UploadSubjectView(check_group_mixin, CreateView):
    model = Subject
    form_class = SubjectForm
    success_url = reverse_lazy('core-home')
    template_name = 'core/upload_subject.html'



class LookupAPIView(generics.ListAPIView):
    serializer_class = LookupSerializers

    def get_queryset(self):
        queryset = Lookup.objects.all()
        src_key = self.request.query_params.get('lookup_type', None)
        print('what is the value of src_key')
        print(src_key)
        if src_key is not None:
            # queryset = queryset.filter(sono=src_key).order_by('drno').last()
            # queryset = queryset.filter(sono=src_key).order_by('drno')
            # queryset = queryset.filter(lookup_type=src_key,active="Yes").order_by('sequence').reverse()[:1]
            queryset = queryset.filter(lookup_type=src_key, active="Yes").order_by('sequence')
        print(queryset)
        return queryset

# RMC 0927
# from .models import Post

#
# def home(request):
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'core/home.html', context)
#
#
# class PostListView(ListView):
#     model = Post
#     template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
#     context_object_name = 'posts'
#     ordering = ['-date_posted']
#     paginate_by = 5
#
#
# class UserPostListView(ListView):
#     model = Post
#     template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
#     context_object_name = 'posts'
#     paginate_by = 5
#
#     def get_queryset(self):
#         user = get_object_or_404(User, username=self.kwargs.get('username'))
#         return Post.objects.filter(author=user).order_by('-date_posted')
#
#
# class PostDetailView(DetailView):
#     model = Post
#
#
# class PostCreateView(LoginRequiredMixin, CreateView):
#     model = Post
#     fields = ['title', 'content']
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)
#
#
# class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     model = Post
#     fields = ['title', 'content']
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)
#
#     def test_func(self):
#         post = self.get_object()
#         if self.request.user == post.author:
#             return True
#         return False
#
#
# class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
#     model = Post
#     success_url = '/'
#
#     def test_func(self):
#         post = self.get_object()
#         if self.request.user == post.author:
#             return True
#         return False
#
#
# def about(request):
#     return render(request, 'core/about.html', {'title': 'About'})
#
# RMC 0927

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Open Sans Bold-->
   <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'miika/css/main.css' %}">

    {% if title %}
        <title>MiiKA Blog - {{ title }}</title>
    {% else %}
        <title>MiiKA Blog</title>
    {% endif %}
</head>
<body class="blog">
    <header class="site-headerblog">

      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #1A73E8;">

        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'miika-home' %}">MiiKA</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'miika-about' %}">About Us</a>
              <a class="nav-item nav-link" href="{% url 'miika-contact' %}">Contact Us</a>
              {% if user.is_authenticated %}
                <!--<a class="nav-item nav-link" href="{% url 'class_subject_list' %}">Online Library</a>-->
                <a class="nav-item nav-link" href="{% url 'blog-home' %}">Blog</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}

                <!--<a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>-->
                {% if user.get_full_name != "" %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">{{user.get_full_name}}</a>
                 {% else %}
                 <a class="nav-item nav-link" href="{% url 'profile' %}">{{user.username}}</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <!--<a class="nav-item nav-link" href="{% url 'register' %}">Register</a>-->
              {% endif %}
               {% for group in user.groups.all %}
                    {% if group.name == "miika_admin" %}
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                {% endfor %}
            </div>
          </div>
        </div>
      </nav>
     </nav>

    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-14">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <!--<div class="col-md-4">-->
          <!--<div class="content-section">-->
            <!--<h3>Our Sidebar</h3>-->
            <!--<p class='text-muted'>You can put any information here you'd like.-->
              <!--<ul class="list-group">-->
                <!--<li class="list-group-item list-group-item-light">Latest Posts</li>-->
                <!--<li class="list-group-item list-group-item-light">Announcements</li>-->
                <!--<li class="list-group-item list-group-item-light">Calendars</li>-->
                <!--<li class="list-group-item list-group-item-light">etc</li>-->
              <!--</ul>-->
            <!--</p>-->
          <!--</div>-->
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% block js %} {% endblock js %}
</body>
</html>

core/templates/core/class_subject_list.html
{% extends 'core/subject_list.html' %}

{% block content_header %}
  <h2>Books (Class-Based View)</h2>
  <p>
    <a href="{% url 'class_upload_subject' %}" class="btn btn-primary">Upload Subject</a>
  </p>
{% endblock %}

core/templates/core/edit_subject.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}




{% block content %}



<br>
<br>
<br>

  <h2>Save subject</h2>
  <form method="post" enctype="multipart/form-data" action="/core/class/subjects/update/{{subject.id}}">
    {% csrf_token %}
    <!--{{ form|crispy }}-->
     {{ form.year_level|as_crispy_field }}
     <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.subject_code|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.subject_description|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.lesson_number|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.lesson_name|as_crispy_field }}
      </div>
         <div class="form-group col-md-6 mb-0">
        {{ form.subject_type|as_crispy_field }}
      </div>
    </div>
    {{ form.cover|as_crispy_field }}
    {{ form.file|as_crispy_field }}
    <button type="submit" class="btn btn-primary">Save subject</button>
  </form>
<!--<h2>JSON</h2>-->
<!--<input class="form-control" id="id_subject_code3" value="jQuery" />-->

{% endblock content %}
{% block js %}

{% load static %}
<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/flatly/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'miika/css/jquery.inputpicker.css' %}?v3" >
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<script src="{% static 'miika/js/jquery.inputpicker.js' %}?v3"></script>
<script type="text/javascript">
//alert("oppkss");

$('#id_subject_code').inputpicker({
    <!--url:'http://127.0.0.1:8000/core/api/lookup/?format=json&lookup_type=2',-->
    url:'https://immense-shore-17080.herokuapp.com/core/api/lookup/?format=json&lookup_type=2',
    <!--fields:['id','name','description','value'],-->
    fields:['name','description'],
    fieldText:'name',
    fieldValue:'value',
    headShow: true,
});

$('#id_subject_code').change(function(input){
 var selected_row = $('#id_subject_code').inputpicker('data_highlighted');
 console.log(selected_row);
	//alert(selected_row.description);
	$('#id_subject_description').val(selected_row.description)
	//alert("oopsw");
 });

 <!--$('#id_subject_code').on('change_highlight.inputpicker',function(input){-->
  <!--alert("oops2");-->
<!--});-->


</script>




{% endblock js %}

core/templates/core/error403.html
{% extends "myapp/base.html" %}


{% block content %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>403 Forbidden</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style type="text/css">
      h1 {
        font-size: 1200%;
        font-weight: 900;
      }
      #error-page {
        padding-top: 10%;
        text-align: center
      }
    </style>
</head>
<body>
  <div class="container">
    <div class="row">
        <div id="error-page" class="col-md-12">
            <h1>403</h1>
            <h2>You are not authorized to view this page</h2>
            <br>
            <a class="btn btn-primary" href="/">Return to the main page</a>
        </div>
    </div>
  </div>
</body>
</html>

{% endblock content %}

core/templates/core/upload_subject.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}




{% block content %}



<br>
<br>
<br>

  <h2>Upload subject</h2>
  <form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <!--{{ form|crispy }}-->
     {{ form.year_level|as_crispy_field }}
     <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.subject_code|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.subject_description|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.lesson_number|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.lesson_name|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.subject_type|as_crispy_field }}
      </div>
    </div>
    {{ form.cover|as_crispy_field }}
    {{ form.file|as_crispy_field }}
    <button type="submit" class="btn btn-primary">Upload subject</button>
  </form>
<!--<h2>JSON</h2>-->
<!--<input class="form-control" id="id_subject_code3" value="jQuery" />-->

{% endblock content %}
{% block js %}

{% load static %}
<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/flatly/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'miika/css/jquery.inputpicker.css' %}?v3" >
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<script src="{% static 'miika/js/jquery.inputpicker.js' %}?v3"></script>
<script type="text/javascript">
//alert("oppkss");

$('#id_subject_code').inputpicker({
    <!--url:'http://127.0.0.1:8000/core/api/lookup/?format=json&lookup_type=2',-->
    url:'https://immense-shore-17080.herokuapp.com/core/api/lookup/?format=json&lookup_type=2',
    <!--fields:['id','name','description','value'],-->
    fields:['name','description'],
    fieldText:'name',
    fieldValue:'value',
    headShow: true,
});

$('#id_subject_code').change(function(input){
 var selected_row = $('#id_subject_code').inputpicker('data_highlighted');
 console.log(selected_row);
	//alert(selected_row.description);
	$('#id_subject_description').val(selected_row.description)
	//alert("oopsw");
 });

 <!--$('#id_subject_code').on('change_highlight.inputpicker',function(input){-->
  <!--alert("oops2");-->
<!--});-->


</script>




{% endblock js %}